services:
  # On définit notre service de base de données
  db-dev:
    image: postgres:15
    container_name: postgres_local
    restart: always
    environment:
      # Ces variables créent automatiquement la DB et l'utilisateur au démarrage
      POSTGRES_DB: dev
      POSTGRES_USER: usedev
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      # Optionnel : pour que tes données ne disparaissent pas quand tu coupes Docker
      - db_data:/var/lib/postgresql/data
      # Magique : tout fichier .sql dans ce dossier est exécuté au premier lancement
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
