version: '3.8'

services:
  db-dev:
    container_name: postgres_local
    image: postgres:15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: usedev
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"  # On garde le 5433 pour Ã©viter le conflit
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin_local
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # ICI on charge le port 8080 !
    depends_on:
      - db-dev

volumes:
  db_data:
